### ISSUE TITLE
readQuery doesn't exist on cache

### ISSUE THREAD

**Issue by tomanagle** [Mike-Gibson/mock-apollo-client#4] opened 2020-02-26 01:15 UTC
Hi, 

Firstly, greate library! It's helped solve a difficult problem and has made testing really easy.

I've come across a problem when reading and writing to the cache manually in the [update method](https://www.apollographql.com/docs/react/data/mutations/#options) on the mutation hook. 

The code looks like this:
```javascript
update: (cache, result) => {
    const currentOrgData = cache.readQuery({
      query: MY_QUERY,
      variables: {
        input: {
          id
         }
       }
})
```

During the test, an error appears in the console that reads:
```
 Invariant Violation: Can't find field Organisation({"input":{}}) on obje
ct undefined.
```

Organisation is what the mocked ```MY_QUERY``` returns.

If I add mockClient.cache.readQuery = jest.fn() above the render method in the test, everything works perfectly.

Would it be worth adding a ```readQuery``` to the cache object, or an option to mock the method in the setRequestHandler function? I'm guessing the same applies for the ```writeData``` method.

**Comment by Mike-Gibson** [comment] 2020-02-28 21:38
Hi, thanks for using the library, and for raising this issue. 

I haven't used the update method personally, which is why I've not come across this before.

The mock apollo client just uses the in-memory cache, so I'm not sure where the issue is coming from. I'll hopefully have some time over the weekend to have a look. If you have a small repro that would really help too, no worries if not tho.

**Comment by Mike-Gibson** [comment] 2020-02-29 21:56
I had a quick look into this and couldn't find any issues in mock-apollo-client. I added a test for `readQuery` in a separate branch [here](https://github.com/Mike-Gibson/mock-apollo-client/blob/issue/4/src/mockClient.integration.test.ts#L89) and it seems to pass as expected. This test doesn't use react-apollo but I think it should be good enough.

I read up on `readQuery` and when there is no data to return, it will throw the `Invariant Violation` error. So in the test I added, if I change the ID variable so it doesn't match any data in the cache, it also throws the `Invariant Violation`.

Could you please double check that the variables you're passing to `readQuery` are the same as the ones passed to the original query? As I spotted in the error message - `{"input":{}}` - which might just be strange serialisation of the variables, or it might mean that id is undefined there.
If that is what you expect, it would be useful to know what's in the cache at that point in time. One way to do that would be to call `cache.extract()` just before you call `readQuery`.

Please let me know what you find. I'm happy to look further into it if you think it is still an issue with mock-apollo-client. Again, if you could provide a repro that would be a great help.

**Comment by Mike-Gibson** [comment] 2020-04-25 18:33
Hi @tomanagle, just wondering if you were still having an issue when writing to the cache manually?

**Comment by tomanagle** [comment] 2020-04-26 00:36
@Mike-Gibson sorry, I totally forgot about this issue.

I haven't come across the issue since. I will look through the code to see where it was and see if it's still an issue.

Thank you!

**Comment by Mike-Gibson** [comment] 2020-06-11 16:28
Closing for now. Please feel free to re-open if you run into the issue again.

**Closed as completed by Mike-Gibson** 2020-06-11 16:28 UTC
Labels: v0.x (Apollo 2)
